export const actionTypes = {
  GET_OUTPUT_MOVEMENTS_REQUESTED: 'GET_OUTPUT_MOVEMENTS_REQUESTED',
  GET_OUTPUT_MOVEMENTS_COMPLETED: 'GET_OUTPUT_MOVEMENTS_COMPLETED',
  GET_OUTPUT_MOVEMENTS_FAILED: 'GET_OUTPUT_MOVEMENTS_FAILED',
};
